/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmSecondDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/Addmemberdetails`; params?: Router.UnknownInputParams; } | { pathname: `/../services/reducxStore`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmBasicDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmFirst`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FirstLoginProView`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FirstTimePackagePlan`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/PaymentGatewayView`; params?: Router.UnknownInputParams; } | { pathname: `/../store/packageSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/AddNewFarmSecondDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/Addmemberdetails`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/reducxStore`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/AddNewFarmBasicDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/AddNewFarmFirst`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/FirstLoginProView`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/FirstTimePackagePlan`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/PaymentGatewayView`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/packageSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../component/Farm/AddNewFarmSecondDetails${`?${string}` | `#${string}` | ''}` | `/../component/Farm/Addmemberdetails${`?${string}` | `#${string}` | ''}` | `/../services/reducxStore${`?${string}` | `#${string}` | ''}` | `/../component/Farm/AddNewFarmBasicDetails${`?${string}` | `#${string}` | ''}` | `/../component/Farm/AddNewFarmFirst${`?${string}` | `#${string}` | ''}` | `/../component/Farm/FirstLoginProView${`?${string}` | `#${string}` | ''}` | `/../component/Farm/FirstTimePackagePlan${`?${string}` | `#${string}` | ''}` | `/../component/Farm/PaymentGatewayView${`?${string}` | `#${string}` | ''}` | `/../store/packageSlice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmSecondDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/Addmemberdetails`; params?: Router.UnknownInputParams; } | { pathname: `/../services/reducxStore`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmBasicDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/AddNewFarmFirst`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FirstLoginProView`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FirstTimePackagePlan`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/PaymentGatewayView`; params?: Router.UnknownInputParams; } | { pathname: `/../store/packageSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
