/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../component/AddFixedAsset`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FarmAssertsFixedView`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FarmDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../component/GoviCapital/InvestmentRequestForm`; params?: Router.UnknownInputParams; } | { pathname: `/../component/RequestInspection/RequestHistory`; params?: Router.UnknownInputParams; } | { pathname: `/../component/types`; params?: Router.UnknownInputParams; } | { pathname: `/../environment/environment`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/AddFixedAsset`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/FarmAssertsFixedView`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/Farm/FarmDetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/GoviCapital/InvestmentRequestForm`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/RequestInspection/RequestHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/../component/types`; params?: Router.UnknownOutputParams; } | { pathname: `/../environment/environment`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/../component/AddFixedAsset${`?${string}` | `#${string}` | ''}` | `/../component/Farm/FarmAssertsFixedView${`?${string}` | `#${string}` | ''}` | `/../component/Farm/FarmDetailsScreen${`?${string}` | `#${string}` | ''}` | `/../component/GoviCapital/InvestmentRequestForm${`?${string}` | `#${string}` | ''}` | `/../component/RequestInspection/RequestHistory${`?${string}` | `#${string}` | ''}` | `/../component/types${`?${string}` | `#${string}` | ''}` | `/../environment/environment${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../component/AddFixedAsset`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FarmAssertsFixedView`; params?: Router.UnknownInputParams; } | { pathname: `/../component/Farm/FarmDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../component/GoviCapital/InvestmentRequestForm`; params?: Router.UnknownInputParams; } | { pathname: `/../component/RequestInspection/RequestHistory`; params?: Router.UnknownInputParams; } | { pathname: `/../component/types`; params?: Router.UnknownInputParams; } | { pathname: `/../environment/environment`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
